### ISSUE TITLE
Pfetch and error

### ISSUE THREAD

**Issue by Oogaboogaman21** [carince/bloxflip-autocrash#43]
PFETCH  Fetching user data failed.
Error: undefined
How do I fix this?

**Comment by Oogaboogaman21** [comment]
nvm I'm dum

**Comment by carince** [comment]
The main has not been updated for a while, so I recommend using the dev branch. You would need to delete or rename your existing bloxflip-autocrash so we can ensure that switching goes smoothly. 

Assuming you have already deleted/renamed your old autocrash folder, do the following:
1. Open PowerShell in a folder where you would want your bloxflip-autocrash folder to be.
2. Run `git clone https://github.com/carince/bloxflip-autocrash.git` and then `cd bloxflip-autocrash`.
3. Switch the branch by using `git checkout dev`.
4. [Follow the installation process](https://github.com/carince/bloxflip-autocrash/blob/dev/docs/1_INSTALLING.md).

**Comment by carince** [comment]
Inactive
