### ISSUE TITLE
Websocket closed unexpectedly

### ISSUE THREAD

**Issue by MrSteve476** [carince/bloxflip-autocrash#61]
I start and it works fine, but then in around 4 minutes the next message appears, and it doesn't respond anymore:

![websocket bug](https://github.com/carince/bloxflip-autocrash/assets/152318730/69b91e17-b38b-4019-998a-01c395e30c2c)

**Comment by carince** [comment]
Fixed in a recent commit: [3e985c6](https://github.com/carince/bloxflip-autocrash/commit/3e985c660f41d92a21b46256d58f3556d79acb09)
